[workspace]
members = [
    "crates/aivi",
    "crates/aivi_core",
    "crates/aivi_driver",
    "crates/aivi_http_server",
    "crates/aivi_lsp",
    "crates/aivi_native_runtime",
    "crates/doc_index_gen",
]
exclude = [
    "crates/aivi/tests/fixtures/native_smoke",
]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
