name = "AIVI"
grammar = "aivi"
path_suffixes = ["aivi"]
tab_size = 2
hard_tabs = false
line_comments = ["// "]
block_comment = { start = "/* ", end = " */" }
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "`", end = "`", close = true, newline = false },
]
autoclose_before = ";:.,=}])>"
